---
release_tags: &release_tags
  tags:
    only: /^v\d+(\.\d+){2}(-.*)?$/

# "Include" for unit tests definition.
unit_tests: &unit_tests
  steps:
    - checkout
    - run:
        name: Install modules and dependencies.
        command: npm install
    - run:
        name: Run unit tests.
        command: npm test
    - run:
        name: Submit coverage data to codecov.
        command: npm run codecov
        when: always

version: 2.0
workflows:
  version: 2
  tests:
    jobs:
      - node10:
          filters: *release_tags
      - node12:
          filters: *release_tags
      - node13:
          filters: *release_tags
      - publish_npm:
          requires:
            - node10
            - node12
            - node13
          filters:
            branches:
              ignore: /.*/
            <<: *release_tags

jobs:
  node10:
    docker:
      - image: node:10
        user: node
    <<: *unit_tests
  node12:
    docker:
      - image: node:12
        user: node
    <<: *unit_tests
  node13:
    docker:
      - image: node:13
        user: node
    <<: *unit_tests

  publish_npm:
    docker:
      - image: node:12
        user: node
    steps:
      - checkout
      - run:
          name: Set NPM authentication.
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run:
          name: Install modules and dependencies.
          command: npm install
      - run:
          name: Publish the module to npm.
          command: npm publish
